version: '2'
services:
  web:
    build:
      context: .
      dockerfile: app/Dockerfile.preview
    environment:
      VIRTUAL_HOST: $COMPOSE_VIRTUAL_HOST
    depends_on:
     - redis
  redis:
    image: redis
