FROM php:5.6-cli
# phpize deps
RUN apt-get update && apt-get install -y \
		git \
    zip \
    unzip \
	--no-install-recommends && rm -r /var/lib/apt/lists/*
WORKDIR /opt/app
EXPOSE 8080
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
RUN /usr/local/bin/composer install
CMD [ "php", "-S", "0.0.0.0:8080", "-c", "configs/php.ini", "./web/index.php" ]
